config/routes.rb
Rails.application.routes.draw do

  root :to => 'messages#index'

  resources :messages do
    member do
      post :prescription
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hack_attempt.rb
class HackAttempt < StandardError
  def message
    'Original message was not the expected one.'
  end
end

app/models/inbox.rb
class Inbox < ApplicationRecord

  belongs_to :user
  has_many :messages
  
  def update_unread
    if user == User.default_doctor # <-- omit this check, to update all inboxes
      self.unread_emails = messages.unread.count
      save!
    end
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :inbox
  belongs_to :outbox
  attr_accessor :original_message_id
  scope :unread, -> { where(read: false) }
  WEEK = 7

  def self.build(body, original_message_id)
    message = Message.new(body: body, original_message_id: original_message_id)
    message.outbox = User.current.outbox
    message.set_inbox
    message
  end

  def set_inbox
    original_message = prevent_hacks(@original_message_id)
    days_since_original_message = (DateTime.now.to_date - original_message.created_at.to_date).to_i
    self.inbox = if days_since_original_message <= WEEK
                   User.default_doctor.inbox
                 else
                   User.default_admin.inbox
                 end
  end

  def set_to_read
    unless read?
      self.read = true
      inbox.update_unread if save
    end
  end

  def self.build_prescription_request(original_message_id)
    message = Message.new(body: "I've lost my script, please issue a new one at a charge of €10. Message: #{original_message_id}")
    message.outbox = User.current.outbox
    message.inbox = User.default_admin.inbox
    message
  end

  def self.request_prescription(original_message_id)
    Payment.transaction do
      payment = Payment.new(user: User.current)
      result = { id: '', notice: '' }
      if payment.save
        message = Message.build_prescription_request(original_message_id)
        message.prevent_hacks(original_message_id)
        if message.save
          if PaymentProviderFactory.debit_card(User.current)
            result[:id] = original_message_id
            result[:notice] = 'Your request was received! Your prescription will be sent to your inbox.'
          else
            # Try again in 15 minutes. We do not want to lose the payment.
            Message.delay(run_at: 15.minutes.from_now).request_prescription
            raise ActiveRecord::Rollback, 'Call to Payment API failed!'
          end
        else
          # Try again 15 minutes. We do not want to lose the payment.
          Message.delay(run_at: 15.minutes.from_now).request_prescription
          raise ActiveRecord::Rollback, 'Prescription request failed!'
        end
      else
        # Try again 15 minutes. We do not want to lose the payment.
        Message.delay(run_at: 15.minutes.from_now).request_prescription
        raise ActiveRecord::Rollback, 'Payment failed!'
      end
      result
    end
  end

  def prevent_hacks(original_message_id)
    raise OriginalMessageNotFound if original_message_id.blank?

    original_message = Message.find(original_message_id)
    if original_message.nil? ||
       original_message.inbox.user != self.outbox.user ||
       original_message.outbox != User.default_doctor.outbox
      raise HackAttempt
    end

    original_message
  end
end

app/models/original_message_not_found.rb
class OriginalMessageNotFound < StandardError
  def message
    'Original message was not found.'
  end
end

app/models/outbox.rb
class Outbox < ApplicationRecord

  belongs_to :user
  has_many :messages

end

app/models/payment.rb
class Payment < ApplicationRecord

  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord

  has_one :inbox
  has_one :outbox
  has_many :payments
  has_many :messages

  scope :patient, -> { where(is_patient: true) }
  scope :admin, -> { where(is_admin: true) }
  scope :doctor, -> { where(is_doctor: true) }

  def self.current
    User.patient.first
  end

  def self.default_admin
    User.admin.first
  end

  def self.default_doctor
    User.doctor.first
  end

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def show
    @message = Message.find(params[:id])
    @message.set_to_read
  end

  def new
    @message = Message.new(original_message_id: params[:original_message_id])
  end

  def create
    @message = Message.build(params[:message][:body], params[:message][:original_message_id])
    if @message.save
      @message.inbox.update_unread
      redirect_to message_path(id: params[:message][:original_message_id]), notice: 'Your reply was sent!'
    else
      redirect_to new_message_path(original_message_id: params[:message][:original_message_id]), notice: 'Your reply was not sent. Please try again'
    end
  rescue OriginalMessageNotFound, ActiveRecord::RecordNotFound
    render file: "#{Rails.root}/public/404.html", layout: false, status: 404
  rescue HackAttempt
    render file: "#{Rails.root}/public/403.html", layout: false, status: 403
  end

  def prescription
    result = Message.request_prescription(params[:original_message_id])
    if result.blank?
      redirect_to root_path, notice: 'Pending payment! Bear with us while we process your request.'
    else
      redirect_to message_path(id: result[:id]), notice: result[:notice]
    end
  rescue OriginalMessageNotFound, ActiveRecord::RecordNotFound
    render file: "#{Rails.root}/public/404.html", layout: false, status: 404
  rescue HackAttempt
    render file: "#{Rails.root}/public/403.html", layout: false, status: 403
  end

  private

  def message_params
    params.require(:message).permit(:body, :original_message_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NuaMessaging</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-light">
    <%= render 'navigation/header' %>

    <main role="main" class="container">
      <%= yield %>
    </main>
  </body>
</html>

app/views/messages/index.html.erb
<div class="my-3 p-3 bg-white rounded shadow-sm">
  <h6 class="border-bottom border-gray pb-2 mb-0">Inbox</h6>
  <% User.current.inbox.messages.each do |message| %>
    <%= link_to message do %>
      <div class="media text-muted pt-3">
        <svg class="bd-placeholder-img mr-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 32x32"><title>Placeholder</title><rect width="100%" height="100%" fill="#007bff"></rect><text x="50%" y="50%" fill="#007bff" dy=".3em">32x32</text></svg>
        <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
          <strong class="d-block text-gray-dark"><%= message.outbox.user.first_name %> <%= message.outbox.user.last_name %></strong>
          <%= message.body.truncate(45) %>
        </p>
      </div>
    <% end %>
  <% end %>
  <% flash.each do |name, msg| -%>
    <%= content_tag :div, msg, class: name %>
  <% end -%>
  <small class="d-block text-right mt-3">
    <a href="#">All updates</a>
  </small>
</div>

app/views/messages/new.html.erb
<div class="card mt-3">
  <h5 class="card-header">
    New Message
  </h5>

  <div class="card-body">
    <% flash.each do |name, msg| -%>
      <%= content_tag :div, msg, class: name %>
    <% end -%>
    <%= form_for @message do |f| %>
      <div class="form-group py-3">
        <%= f.text_area :body, class: "form-control", rows: 3 %>
        <%= f.hidden_field :original_message_id%>
      </div>

      <div class="form-group mb-0 text-right">
        <%= f.submit 'Send Message', class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>

</div>

app/views/messages/show.html.erb
<div class="card my-3 ">
  <h5 class="card-header">
    <% if @message.outbox.user.is_doctor? %>Dr.<% end %>
    <%= @message.outbox.user.full_name %>
  </h5>
  <div class="card-body">
    <p class="card-text"><%= @message.body %></p>
    <%= link_to "Reply", new_message_path(original_message_id: @message.id.to_s), class: "btn btn-primary" %>
    <%= link_to "I've lost my prescription", prescription_message_path(original_message_id: @message.id.to_s), method: :post, class: "btn btn-primary" %>
  </div>
  <% flash.each do |name, msg| -%>
    <%= content_tag :div, msg, class: name %>
  <% end -%>
</div>

app/views/navigation/_header.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="#">Nua Messaging</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to messages_path, class: 'nav-link' do %>
          Inbox
        <% end  %>
      </li>
    </ul>
  </div>
</nav>